spring.application.name=sgp-api

# Propriedades de conexao com banco de dados
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/sgp_db
spring.datasource.username=root
spring.datasource.password=root
